---
apiVersion: v1
kind: Namespace
metadata:
  name: ldap
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-admin-password
  namespace: ldap
type: Opaque
stringData:
  adminpassword: admin123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-bootstrap
  namespace: ldap
data:
  bootstrap.ldif: |
    dn: ou=users,dc=traefik,dc=io
    objectClass: organizationalUnit
    ou: users

    dn: cn=jdoe,dc=traefik,dc=io
    objectClass: inetOrgPerson
    cn: jdoe
    sn: Doe
    uid: jdoe
    userPassword: 1234

    dn: uid=jdoe,ou=users,dc=traefik,dc=io
    objectClass: inetOrgPerson
    objectClass: posixAccount
    cn: Joe Doe
    sn: Doe
    uid: jdoe
    mail: jdoe@traefik.io
    uidNumber: 1000
    gidNumber: 1000
    homeDirectory: /home/jdoe
    userPassword: 12345

    dn: uid=asmith,ou=users,dc=traefik,dc=io
    objectClass: inetOrgPerson
    objectClass: posixAccount
    cn: Alice Smith
    sn: Smith
    uid: asmith
    mail: asmith@traefik.io
    uidNumber: 1001
    gidNumber: 1001
    homeDirectory: /home/asmith
    userPassword: alicepwd

    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      volumes:
      - name: bootstrap-config
        configMap:
          name: ldap-bootstrap
      - name: bootstrap-data
        emptyDir: {}
      initContainers:
      - name: init-ldif
        image: busybox:1.36
        command: ["sh", "-c", "cp /ldif-config/bootstrap.ldif /ldif-data/"]
        volumeMounts:
        - name: bootstrap-config
          mountPath: /ldif-config
        - name: bootstrap-data
          mountPath: /ldif-data
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        ports:
        - containerPort: 389
        - containerPort: 636
        env:
        - name: LDAP_ORGANIZATION
          value: "Traefik Io"
        - name: LDAP_DOMAIN
          value: "traefik.io"
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-admin-password
              key: adminpassword
        volumeMounts:
        - name: bootstrap-data
          mountPath: /ldif-data
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - >
                  set -e;
                  for i in $(seq 1 10); do
                    ldapsearch -x -H ldap://localhost -b "" -s base "objectclass=*" >/dev/null 2>&1 && break;
                    echo -n ".";
                    sleep 1;
                  done;
                  if [ $(ldapsearch -x -H ldap://localhost -b "ou=users,dc=traefik,dc=io" -s base '(objectClass=*)' 2>/dev/null | grep -c "numEntries: 1") -eq 0 ]; then
                    echo 'Importing LDIF data...';
                    ldapadd -x -D "cn=admin,dc=traefik,dc=io" -w "$LDAP_ADMIN_PASSWORD" -f /ldif-data/bootstrap.ldif;
                    echo 'LDIF data imported successfully.';
                  else
                    echo 'Data already exists, skipping import.';
                  fi
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: ldap
spec:
  type: ClusterIP
  selector:
    app: openldap
  ports:
  - name: ldap
    port: 389
    targetPort: 389
  - name: ldaps
    port: 636
    targetPort: 636
